"""
export_service.py — The Print Shop
=====================================
Converts blueprints into downloadable files.
- PDF blueprints with forge styling
- Plain text export
- JSON data export

Endpoints:
- POST /export/pdf   — Generate PDF blueprint
- POST /export/text  — Plain text export
- GET  /health
"""

import os
import io
import secrets
import logging
from fastapi import FastAPI, Header, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

logging.basicConfig(level=logging.INFO, format="%(asctime)s [EXPORT] %(levelname)s %(message)s")
log = logging.getLogger("export")

app = FastAPI()

INTERNAL_API_KEY = os.getenv("INTERNAL_API_KEY")

class ExportRequest(BaseModel):
    blueprint:    str
    project_type: str
    junk_desc:    str
    build_id:     int = 0
    user_email:   str = "anonymous"

async def verify(x_internal_key: str):
    if not x_internal_key or not INTERNAL_API_KEY or \
       not secrets.compare_digest(x_internal_key, INTERNAL_API_KEY):
        raise HTTPException(status_code=403, detail="Unauthorized")

@app.get("/health")
async def health():
    return {"status": "healthy"}

@app.post("/export/pdf")
async def export_pdf(req: ExportRequest, x_internal_key: str = Header(None)):
    await verify(x_internal_key)

    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor, black, white
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        from reportlab.lib.units import inch

        buffer = io.BytesIO()
        doc    = SimpleDocTemplate(
            buffer, pagesize=letter,
            topMargin=0.75*inch, bottomMargin=0.75*inch,
            leftMargin=0.75*inch, rightMargin=0.75*inch
        )

        forge_orange = HexColor("#FF6600")
        forge_dark   = HexColor("#1a1a1a")
        forge_grey   = HexColor("#888888")

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "ForgeTitle",
            fontName="Helvetica-Bold",
            fontSize=28,
            textColor=forge_orange,
            spaceAfter=4,
            leading=32
        )
        subtitle_style = ParagraphStyle(
            "ForgeSubtitle",
            fontName="Helvetica",
            fontSize=10,
            textColor=forge_grey,
            spaceAfter=20
        )
        header_style = ParagraphStyle(
            "ForgeHeader",
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=forge_orange,
            spaceBefore=16,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            "ForgeBody",
            fontName="Helvetica",
            fontSize=10,
            textColor=forge_dark,
            leading=16,
            spaceAfter=8
        )
        meta_style = ParagraphStyle(
            "ForgeMeta",
            fontName="Helvetica",
            fontSize=8,
            textColor=forge_grey
        )

        story = []

        # Header
        story.append(Paragraph("THE BUILDER", title_style))
        story.append(Paragraph("AoC3P0 Systems · AI-Powered Engineering Forge · Round Table Blueprint", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=2, color=forge_orange))
        story.append(Spacer(1, 12))

        # Build info
        story.append(Paragraph(f"PROJECT: {req.project_type.upper()}", header_style))
        story.append(Paragraph(f"PARTS: {req.junk_desc}", body_style))
        if req.build_id:
            story.append(Paragraph(f"BUILD ID: #{req.build_id}", meta_style))
        story.append(HRFlowable(width="100%", thickness=1, color=HexColor("#333333")))
        story.append(Spacer(1, 12))

        # Blueprint content
        story.append(Paragraph("BLUEPRINT", header_style))
        for line in req.blueprint.split("\n"):
            line = line.strip()
            if not line:
                story.append(Spacer(1, 6))
            elif line.startswith("##"):
                clean = line.replace("#", "").strip()
                story.append(Paragraph(clean, header_style))
            elif line.startswith("#"):
                clean = line.replace("#", "").strip()
                story.append(Paragraph(clean, header_style))
            else:
                # Escape HTML chars for reportlab
                safe = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(safe, body_style))

        # Footer
        story.append(Spacer(1, 20))
        story.append(HRFlowable(width="100%", thickness=1, color=forge_orange))
        story.append(Spacer(1, 6))
        story.append(Paragraph(
            "Generated by The Builder · AoC3P0 Systems · Always wear PPE · Build responsibly.",
            meta_style
        ))

        doc.build(story)
        buffer.seek(0)

        filename = f"blueprint_{req.project_type.replace(' ', '_').lower()}_{req.build_id}.pdf"
        return StreamingResponse(
            buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )

    except ImportError:
        raise HTTPException(
            status_code=500,
            detail="PDF generation requires reportlab. Add 'reportlab' to requirements."
        )
    except Exception as e:
        log.error(f"PDF generation error: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/export/text")
async def export_text(req: ExportRequest, x_internal_key: str = Header(None)):
    await verify(x_internal_key)

    content = f"""
================================================================================
THE BUILDER — AoC3P0 SYSTEMS
AI-Powered Engineering Forge · Round Table Blueprint
================================================================================

PROJECT:  {req.project_type.upper()}
PARTS:    {req.junk_desc}
BUILD ID: #{req.build_id}

================================================================================
BLUEPRINT
================================================================================

{req.blueprint}

================================================================================
Generated by The Builder · AoC3P0 Systems
Always wear PPE. Build responsibly.
================================================================================
""".strip()

    buffer   = io.BytesIO(content.encode("utf-8"))
    filename = f"blueprint_{req.project_type.replace(' ', '_').lower()}_{req.build_id}.txt"

    return StreamingResponse(
        buffer,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
